name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pandoc
        uses: gbraad-actions/pandoc@main
        with:
          source: "docs/*.md"
          output-format: pdf
          output-dir: pdf-output

      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: ./pdf-output/*.pdf
