name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        uses: gbraad-actions/fedora-action@main
        with:
          dnf-packages: cowsay
          run: |
            cowsay Hello
